CREATE TABLE CLASE (
	"DIA"	TEXT CHECK("DIA" IN ('LUNES', 'MARTES', 'MIÉRCOLES', 'JUEVES', 'VIERNES', 'SÁBADO', 'DOMINGO')),
	"HORA"	TEXT NOT NULL,
	"DNI_EMPLE"	TEXT,
	"ID_INSTALACION"	INTEGER,
	PRIMARY KEY("DIA","HORA","ID_INSTALACION"),
	FOREIGN KEY("ID_INSTALACION") REFERENCES "INSTALACION"("ID"),
	FOREIGN KEY("DNI_EMPLE") REFERENCES "EMPLEADO"("DNI")
);


CREATE TABLE CLIENTE (
	"DNI"	TEXT,
	"APENOM"	TEXT NOT NULL,
	"DIRECCION"	TEXT NOT NULL,
	"NUM_CUENTA"	INTEGER NOT NULL,
	"CORREO"	TEXT,
	"TELEF"	TEXT,
	PRIMARY KEY("DNI")
);


CREATE TABLE CLIENTE_INSTALACION (
	"ID"	INTEGER,
	"DIA"	TEXT NOT NULL,
	"HORA"	TEXT NOT NULL,
	"PAGO"	TEXT CHECK("PAGO" IN ('Sí', 'No')),
	"DNI_CLIENTE"	TEXT,
	"ID_INSTALACION"	INTEGER,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("DNI_CLIENTE") REFERENCES "CLIENTE"("DNI"),
	FOREIGN KEY("ID_INSTALACION") REFERENCES "INSTALACION"("ID")
);

CREATE TABLE DEPORTE (
	"ID"	INTEGER,
	"NOMBRE"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);

CREATE TABLE EMPLEADO (
	"DNI"	TEXT,
	"APENOM"	TEXT NOT NULL,
	"DIRECCION"	TEXT NOT NULL,
	"PASS"	TEXT NOT NULL,
	"ROL"	TEXT CHECK("ROL" IN ('Administrador', 'Administrativo', 'Monitor')),
	"CORREO"	TEXT NOT NULL,
	"TELEFONO"	TEXT NOT NULL,
	PRIMARY KEY("DNI")
);

CREATE TABLE INSTALACION (
	"ID"	INTEGER,
	"TIPO"	TEXT CHECK("TIPO" IN ('Gimnasio', 'Pista', 'Campo', 'Piscina')),
	PRIMARY KEY("ID" AUTOINCREMENT)
);

CREATE TABLE INSTALACION_DEPORTE (
	"ID_DEPORTE"	INTEGER,
	"ID_INSTALACION"	INTEGER,
	PRIMARY KEY("ID_DEPORTE","ID_INSTALACION"),
	FOREIGN KEY("ID_INSTALACION") REFERENCES "INSTALACION"("ID"),
	FOREIGN KEY("ID_DEPORTE") REFERENCES "DEPORTE"("ID")
);