CREATE TABLE CLIENTE(
    DNI VARCHAR2(9) CONSTRAINT CLI_DNI_PK PRIMARY KEY,
    APENOM VARCHAR2(50) CONSTRAINT CLI_APE_NN NOT NULL,
    DIRECCION VARCHAR2(50) CONSTRAINT CLI_DIR_NN NOT NULL,
    PASS TEXT CONSTRAINT CLI_PAS_NN NOT NULL,
    NUM_CUENTA NUMBER(10) CONSTRAINT CLI_NUM_NN NOT NULL
);
CREATE TABLE EMPLEADO(
    DNI VARCHAR2(9) CONSTRAINT EMP_DNI_PK PRIMARY KEY,
    APENOM VARCHAR2(50) CONSTRAINT EMP_APE_NN NOT NULL,
    DIRECCION VARCHAR2(50) CONSTRAINT EMP_DIR_NN NOT NULL,
    PASS TEXT CONSTRAINT EMP_PAS_NN NOT NULL,
    ROL VARCHAR2(14) CONSTRAINT EMP_ROL_CHK CHECK(ROL IN('Administrador', 'Administrativo', 'Monitor'))
);
CREATE TABLE INSTALACION(
    ID_INST NUMBER(3) CONSTRAINT INS_ID_PK PRIMARY KEY,
    TIPO VARCHAR2(8) CONSTRAINT INS_TIP_CHK CHECK(TIPO IN('Gimnasio', 'Pista', 'Campo', 'Piscina')),
    HORA_A TIME CONSTRAINT INS_HA_NN NOT NULL,
    HORA_C TIME CONSTRAINT INS_HC_NN NOT NULL
);
CREATE TABLE DEPORTE(
    ID_DEPORTE NUMBER(2) CONSTRAINT DEP_ID_PK PRIMARY KEY,
    NOMBRE VARCHAR2(15) CONSTRAINT DEP_NOM_NN NOT NULL
);
CREATE TABLE TORNEO(
    ID_TORNEO NUMBER(3) CONSTRAINT TOR_ID_PK PRIMARY KEY,
    FECHA DATE CONSTRAINT TOR_FEC_NN NOT NULL,
    DNI_EMP VARCHAR2(9),
    ID_DEPORTE NUMBER(2),
    CONSTRAINT TOR_EMP_FK FOREIGN KEY(DNI_EMP) REFERENCES EMPLEADO(DNI),
    CONSTRAINT TOR_DEP_FK FOREIGN KEY(ID_DEPORTE) REFERENCES DEPORTE(ID_DEPORTE)
);
CREATE TABLE CLASE(
    ID_CLASE NUMBER (2) CONSTRAINT CLA_ID_PK PRIMARY KEY,
    DIA VARCHAR(9) CONSTRAINT CLA_DIA_CHK CHECK(DIA IN('Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo')),
    HORA TIME CONSTRAINT CLA_HOR_NN NOT NULL,
    DURACION NUMBER(3) CONSTRAINT CLA_DUR_NN NOT NULL,
    DNI_EMP VARCHAR2(9),
    ID_DEPORTE NUMBER(2),
    CONSTRAINT CLA_EMP_FK FOREIGN KEY(DNI_EMP) REFERENCES EMPLEADO(DNI),
    CONSTRAINT CLA_DEP_FK FOREIGN KEY(ID_DEPORTE) REFERENCES DEPORTE(ID_DEPORTE)
);
CREATE TABLE CLIENTE_INSTALACION(
    ID_ALQUILER NUMBER(3) CONSTRAINT CLI_INS_ID_PK PRIMARY KEY,
    FECHA_HORA DATE CONSTRAINT CLI_INS_FEC_NN NOT NULL,
    DURACION NUMBER(3) CONSTRAINT CLI_INS_DUR_NN NOT NULL,
    PAGO VARCHAR2(2) CONSTRAINT CLI_INS_PAG_CHK CHECK(PAGO IN('Sí','No')),
    DNI_CLIENTE VARCHAR2(9) CONSTRAINT CLI_INS_DNI_FK REFERENCES CLIENTE(DNI),
    ID_INST NUMBER(3) CONSTRAINT CLI_INS_ID_INS_FK REFERENCES INSTALACION(ID_INS) 
);
CREATE TABLE CLIENTE_TORNEO(
    DNI_CLIENTE VARCHAR2(9) CONSTRAINT CLI_TOR_DNI_FK REFERENCES CLIENTE(DNI),
    ID_TORNEO NUMBER(3) CONSTRAINT CLI_TOR_ID_TOR_FK REFERENCES TORNEO(ID_TORNEO),
    POSICION NUMBER(3) CONSTRAINT CLI_TOR_POS_NN NOT NULL,
    CONSTRAINT CLI_TOR_PK PRIMARY KEY(DNI_CLIENTE, ID_TORNEO)
);
CREATE TABLE CLIENTE_CLASE(
    DNI_CLIENTE VARCHAR2(9) CONSTRAINT CLI_CLA_DNI_FK REFERENCES CLIENTE(DNI),
    ID_CLASE VARCHAR2(9) CONSTRAINT CLI_CLA_ID_CLA_FK REFERENCES CLASE(ID_CLASE),
    CONSTRAINT CLI_CLA_PK PRIMARY KEY(DNI_CLIENTE, ID_CLASE)
);
CREATE TABLE INSTALACION_DEPORTE(
    ID_DEPORTE NUMBER(2) CONSTRAINT INS_DEP_ID_DEP_FK REFERENCES DEPORTE(ID_DEPORTE),
    ID_INST NUMBER(3) CONSTRAINT INS_DEP_ID_INS_FK REFERENCES INSTALACION(ID_INST),
    CONSTRAINT INS_DEP_PK PRIMARY KEY(ID_DEPORTE, ID_INST)
);